// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type ActiveModules = {
    modules: Array<string>;
    role: string | null;
    organization: Organization | null;
};

export type Client = {
    readonly id: number;
    business_name: string;
    contact?: string;
    readonly created: string;
    readonly modified: string;
};

export type Doctor = {
    readonly id: number;
    name: string;
    specialty?: string;
    hospital?: string;
    is_active?: boolean;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `clinical` - Clínico / hospitalario
 * * `logistics` - Logístico / comercial
 * * `mixed` - Mixto
 */
export type IndustryTypeEnum = 'clinical' | 'logistics' | 'mixed';

export type LogisticsDashboardStats = {
    pending_requisitions: number;
    requisitions_in_transit: number;
    open_sales_orders: number;
    open_purchase_orders: number;
};

export type MedicalDashboardStats = {
    kits_in_transit: number;
    kits_assembling: number;
    active_procedures: number;
};

export type Message = {
    message: string;
};

export type Organization = {
    readonly id: number;
    name: string;
    slug: string;
    industry_type?: IndustryTypeEnum;
    is_active?: boolean;
    readonly created: string;
    readonly modified: string;
};

export type PaginatedClientList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Client>;
};

export type PaginatedDoctorList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Doctor>;
};

export type PaginatedProcedureAssignmentList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ProcedureAssignment>;
};

export type PaginatedProcedureList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Procedure>;
};

export type PaginatedProductList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Product>;
};

export type PaginatedProviderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Provider>;
};

export type PaginatedPurchaseOrderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<PurchaseOrder>;
};

export type PaginatedRfidReadEventList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<RfidReadEvent>;
};

export type PaginatedRfidTagList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<RfidTag>;
};

export type PaginatedRequisitionList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Requisition>;
};

export type PaginatedSalesOrderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SalesOrder>;
};

export type PaginatedSupplyKitList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SupplyKit>;
};

export type PaginatedTechnicianList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Technician>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PatchedClient = {
    readonly id?: number;
    business_name?: string;
    contact?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedDoctor = {
    readonly id?: number;
    name?: string;
    specialty?: string;
    hospital?: string;
    is_active?: boolean;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedProcedure = {
    readonly id?: number;
    procedure_type?: string;
    destination_hospital?: string;
    scheduled_date?: string;
    status?: ProcedureStatusEnum;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedProcedureAssignment = {
    readonly id?: number;
    procedure?: number;
    readonly procedure_type?: string;
    technician?: number;
    readonly technician_name?: string;
    doctor?: number;
    readonly doctor_name?: string;
    role?: RoleEnum;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedProduct = {
    readonly id?: number;
    sku?: string;
    name?: string;
    category?: string;
    unit?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedProvider = {
    readonly id?: number;
    business_name?: string;
    contact?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedPurchaseOrder = {
    readonly id?: number;
    provider?: number;
    readonly provider_name?: string;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<PurchaseOrderLine>;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedRfidTag = {
    readonly id?: number;
    code?: string;
    item_type?: string;
    status?: StatusBf9Enum;
    last_location?: string;
    readonly last_read_at?: string | null;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedRequisition = {
    readonly id?: number;
    origin?: string;
    destination?: string;
    status?: RequisitionStatusEnum;
    requested_at?: string;
    lines?: Array<RequisitionLine>;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedSalesOrder = {
    readonly id?: number;
    client?: number;
    readonly client_name?: string;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<SalesOrderLine>;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedSupplyKit = {
    readonly id?: number;
    name?: string;
    code?: string;
    procedure?: number | null;
    status?: SupplyKitStatusEnum;
    destination_hospital?: string;
    shipped_at?: string | null;
    readonly tag_codes?: Array<string>;
    readonly tag_count?: string;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedTechnician = {
    readonly id?: number;
    name?: string;
    is_active?: boolean;
    readonly created?: string;
    readonly modified?: string;
};

export type PatchedUser = {
    readonly id?: number;
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    readonly created?: string;
    readonly modified?: string;
    last_login?: string | null;
};

export type Procedure = {
    readonly id: number;
    procedure_type: string;
    destination_hospital: string;
    scheduled_date: string;
    status?: ProcedureStatusEnum;
    readonly created: string;
    readonly modified: string;
};

export type ProcedureAssignment = {
    readonly id: number;
    procedure: number;
    readonly procedure_type: string;
    technician: number;
    readonly technician_name: string;
    doctor: number;
    readonly doctor_name: string;
    role: RoleEnum;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `scheduled` - Programado
 * * `in_preparation` - En preparación
 * * `in_transit` - En tránsito
 * * `completed` - Completado
 * * `cancelled` - Cancelado
 */
export type ProcedureStatusEnum = 'scheduled' | 'in_preparation' | 'in_transit' | 'completed' | 'cancelled';

export type Product = {
    readonly id: number;
    sku: string;
    name: string;
    category?: string;
    unit?: string;
    readonly created: string;
    readonly modified: string;
};

export type Provider = {
    readonly id: number;
    business_name: string;
    contact?: string;
    readonly created: string;
    readonly modified: string;
};

export type PurchaseOrder = {
    readonly id: number;
    provider: number;
    readonly provider_name: string;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<PurchaseOrderLine>;
    readonly created: string;
    readonly modified: string;
};

export type PurchaseOrderLine = {
    readonly id: number;
    product: number;
    readonly product_sku: string;
    readonly product_name: string;
    quantity: number;
    unit_price: string;
    readonly line_total: string;
};

export type RfidReadEvent = {
    readonly id: number;
    tag: number;
    readonly tag_code: string;
    timestamp?: string;
    location?: string;
    reader_source?: string;
    event_type: string;
    readonly created: string;
    readonly modified: string;
};

export type RfidReadWebhook = {
    code: string;
    location?: string;
    reader_source?: string;
    event_type: string;
    timestamp?: string;
    item_type?: string;
    status?: StatusBf9Enum;
};

export type RfidTag = {
    readonly id: number;
    code: string;
    item_type?: string;
    status?: StatusBf9Enum;
    last_location?: string;
    readonly last_read_at: string | null;
    readonly created: string;
    readonly modified: string;
};

export type Requisition = {
    readonly id: number;
    origin: string;
    destination: string;
    status?: RequisitionStatusEnum;
    requested_at?: string;
    lines?: Array<RequisitionLine>;
    readonly created: string;
    readonly modified: string;
};

export type RequisitionLine = {
    readonly id: number;
    product: number;
    readonly product_sku: string;
    readonly product_name: string;
    quantity: number;
};

/**
 * * `solicitada` - Solicitada
 * * `aprobada` - Aprobada
 * * `en_transito` - En tránsito
 * * `entregada` - Entregada
 */
export type RequisitionStatusEnum = 'solicitada' | 'aprobada' | 'en_transito' | 'entregada';

/**
 * * `lead_technician` - Técnico principal
 * * `assistant` - Asistente
 * * `supervisor` - Supervisor
 */
export type RoleEnum = 'lead_technician' | 'assistant' | 'supervisor';

export type SalesOrder = {
    readonly id: number;
    client: number;
    readonly client_name: string;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<SalesOrderLine>;
    readonly created: string;
    readonly modified: string;
};

export type SalesOrderLine = {
    readonly id: number;
    product: number;
    readonly product_sku: string;
    readonly product_name: string;
    quantity: number;
    unit_price: string;
    readonly line_total: string;
};

/**
 * * `borrador` - Borrador
 * * `confirmada` - Confirmada
 * * `en_transito` - En tránsito
 * * `entregada` - Entregada
 * * `cancelada` - Cancelada
 */
export type Status086Enum = 'borrador' | 'confirmada' | 'en_transito' | 'entregada' | 'cancelada';

/**
 * * `en_stock` - En stock
 * * `en_transito` - En tránsito
 * * `en_uso` - En uso
 * * `dado_de_baja` - Dado de baja
 */
export type StatusBf9Enum = 'en_stock' | 'en_transito' | 'en_uso' | 'dado_de_baja';

export type SupplyKit = {
    readonly id: number;
    name: string;
    code: string;
    procedure?: number | null;
    status?: SupplyKitStatusEnum;
    destination_hospital?: string;
    shipped_at?: string | null;
    readonly tag_codes: Array<string>;
    readonly tag_count: string;
    readonly created: string;
    readonly modified: string;
};

/**
 * * `armando` - Armando
 * * `lista` - Lista
 * * `en_transito` - En tránsito
 * * `entregada` - Entregada
 * * `usada` - Usada
 */
export type SupplyKitStatusEnum = 'armando' | 'lista' | 'en_transito' | 'entregada' | 'usada';

export type Technician = {
    readonly id: number;
    name: string;
    is_active?: boolean;
    readonly created: string;
    readonly modified: string;
};

export type User = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    readonly created: string;
    readonly modified: string;
    last_login?: string | null;
};

export type ClientWritable = {
    business_name: string;
    contact?: string;
};

export type DoctorWritable = {
    name: string;
    specialty?: string;
    hospital?: string;
    is_active?: boolean;
};

export type OrganizationWritable = {
    name: string;
    slug: string;
    industry_type?: IndustryTypeEnum;
    is_active?: boolean;
};

export type PatchedClientWritable = {
    business_name?: string;
    contact?: string;
};

export type PatchedDoctorWritable = {
    name?: string;
    specialty?: string;
    hospital?: string;
    is_active?: boolean;
};

export type PatchedProcedureWritable = {
    procedure_type?: string;
    destination_hospital?: string;
    scheduled_date?: string;
    status?: ProcedureStatusEnum;
};

export type PatchedProcedureAssignmentWritable = {
    procedure?: number;
    technician?: number;
    doctor?: number;
    role?: RoleEnum;
};

export type PatchedProductWritable = {
    sku?: string;
    name?: string;
    category?: string;
    unit?: string;
};

export type PatchedProviderWritable = {
    business_name?: string;
    contact?: string;
};

export type PatchedPurchaseOrderWritable = {
    provider?: number;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<PurchaseOrderLineWritable>;
};

export type PatchedRfidTagWritable = {
    code?: string;
    item_type?: string;
    status?: StatusBf9Enum;
    last_location?: string;
};

export type PatchedRequisitionWritable = {
    origin?: string;
    destination?: string;
    status?: RequisitionStatusEnum;
    requested_at?: string;
    lines?: Array<RequisitionLineWritable>;
};

export type PatchedSalesOrderWritable = {
    client?: number;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<SalesOrderLineWritable>;
};

export type PatchedSupplyKitWritable = {
    name?: string;
    code?: string;
    procedure?: number | null;
    status?: SupplyKitStatusEnum;
    destination_hospital?: string;
    shipped_at?: string | null;
};

export type PatchedTechnicianWritable = {
    name?: string;
    is_active?: boolean;
};

export type PatchedUserWritable = {
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    last_login?: string | null;
};

export type ProcedureWritable = {
    procedure_type: string;
    destination_hospital: string;
    scheduled_date: string;
    status?: ProcedureStatusEnum;
};

export type ProcedureAssignmentWritable = {
    procedure: number;
    technician: number;
    doctor: number;
    role: RoleEnum;
};

export type ProductWritable = {
    sku: string;
    name: string;
    category?: string;
    unit?: string;
};

export type ProviderWritable = {
    business_name: string;
    contact?: string;
};

export type PurchaseOrderWritable = {
    provider: number;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<PurchaseOrderLineWritable>;
};

export type PurchaseOrderLineWritable = {
    product: number;
    quantity: number;
    unit_price: string;
};

export type RfidReadEventWritable = {
    tag: number;
    timestamp?: string;
    location?: string;
    reader_source?: string;
    event_type: string;
};

export type RfidTagWritable = {
    code: string;
    item_type?: string;
    status?: StatusBf9Enum;
    last_location?: string;
};

export type RequisitionWritable = {
    origin: string;
    destination: string;
    status?: RequisitionStatusEnum;
    requested_at?: string;
    lines?: Array<RequisitionLineWritable>;
};

export type RequisitionLineWritable = {
    product: number;
    quantity: number;
};

export type SalesOrderWritable = {
    client: number;
    status?: Status086Enum;
    total?: string;
    ordered_at?: string;
    lines?: Array<SalesOrderLineWritable>;
};

export type SalesOrderLineWritable = {
    product: number;
    quantity: number;
    unit_price: string;
};

export type SupplyKitWritable = {
    name: string;
    code: string;
    procedure?: number | null;
    status?: SupplyKitStatusEnum;
    destination_hospital?: string;
    shipped_at?: string | null;
};

export type TechnicianWritable = {
    name: string;
    is_active?: boolean;
};

export type UserWritable = {
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    last_login?: string | null;
};

export type ActiveModulesRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/active-modules/';
};

export type ActiveModulesRetrieveResponses = {
    200: ActiveModules;
};

export type ActiveModulesRetrieveResponse = ActiveModulesRetrieveResponses[keyof ActiveModulesRetrieveResponses];

export type ClientsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/clients/';
};

export type ClientsListResponses = {
    200: PaginatedClientList;
};

export type ClientsListResponse = ClientsListResponses[keyof ClientsListResponses];

export type ClientsCreateData = {
    body: ClientWritable;
    path?: never;
    query?: never;
    url: '/api/clients/';
};

export type ClientsCreateResponses = {
    201: Client;
};

export type ClientsCreateResponse = ClientsCreateResponses[keyof ClientsCreateResponses];

export type ClientsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this client.
         */
        id: number;
    };
    query?: never;
    url: '/api/clients/{id}/';
};

export type ClientsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ClientsDestroyResponse = ClientsDestroyResponses[keyof ClientsDestroyResponses];

export type ClientsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this client.
         */
        id: number;
    };
    query?: never;
    url: '/api/clients/{id}/';
};

export type ClientsRetrieveResponses = {
    200: Client;
};

export type ClientsRetrieveResponse = ClientsRetrieveResponses[keyof ClientsRetrieveResponses];

export type ClientsPartialUpdateData = {
    body?: PatchedClientWritable;
    path: {
        /**
         * A unique integer value identifying this client.
         */
        id: number;
    };
    query?: never;
    url: '/api/clients/{id}/';
};

export type ClientsPartialUpdateResponses = {
    200: Client;
};

export type ClientsPartialUpdateResponse = ClientsPartialUpdateResponses[keyof ClientsPartialUpdateResponses];

export type ClientsUpdateData = {
    body: ClientWritable;
    path: {
        /**
         * A unique integer value identifying this client.
         */
        id: number;
    };
    query?: never;
    url: '/api/clients/{id}/';
};

export type ClientsUpdateResponses = {
    200: Client;
};

export type ClientsUpdateResponse = ClientsUpdateResponses[keyof ClientsUpdateResponses];

export type DoctorsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/doctors/';
};

export type DoctorsListResponses = {
    200: PaginatedDoctorList;
};

export type DoctorsListResponse = DoctorsListResponses[keyof DoctorsListResponses];

export type DoctorsCreateData = {
    body: DoctorWritable;
    path?: never;
    query?: never;
    url: '/api/doctors/';
};

export type DoctorsCreateResponses = {
    201: Doctor;
};

export type DoctorsCreateResponse = DoctorsCreateResponses[keyof DoctorsCreateResponses];

export type DoctorsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this doctor.
         */
        id: number;
    };
    query?: never;
    url: '/api/doctors/{id}/';
};

export type DoctorsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DoctorsDestroyResponse = DoctorsDestroyResponses[keyof DoctorsDestroyResponses];

export type DoctorsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this doctor.
         */
        id: number;
    };
    query?: never;
    url: '/api/doctors/{id}/';
};

export type DoctorsRetrieveResponses = {
    200: Doctor;
};

export type DoctorsRetrieveResponse = DoctorsRetrieveResponses[keyof DoctorsRetrieveResponses];

export type DoctorsPartialUpdateData = {
    body?: PatchedDoctorWritable;
    path: {
        /**
         * A unique integer value identifying this doctor.
         */
        id: number;
    };
    query?: never;
    url: '/api/doctors/{id}/';
};

export type DoctorsPartialUpdateResponses = {
    200: Doctor;
};

export type DoctorsPartialUpdateResponse = DoctorsPartialUpdateResponses[keyof DoctorsPartialUpdateResponses];

export type DoctorsUpdateData = {
    body: DoctorWritable;
    path: {
        /**
         * A unique integer value identifying this doctor.
         */
        id: number;
    };
    query?: never;
    url: '/api/doctors/{id}/';
};

export type DoctorsUpdateResponses = {
    200: Doctor;
};

export type DoctorsUpdateResponse = DoctorsUpdateResponses[keyof DoctorsUpdateResponses];

export type InventoryDashboardStatsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inventory/dashboard-stats/';
};

export type InventoryDashboardStatsRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type LogisticsDashboardStatsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logistics/dashboard-stats/';
};

export type LogisticsDashboardStatsRetrieveResponses = {
    200: LogisticsDashboardStats;
};

export type LogisticsDashboardStatsRetrieveResponse = LogisticsDashboardStatsRetrieveResponses[keyof LogisticsDashboardStatsRetrieveResponses];

export type MedicalDashboardStatsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/medical/dashboard-stats/';
};

export type MedicalDashboardStatsRetrieveResponses = {
    200: MedicalDashboardStats;
};

export type MedicalDashboardStatsRetrieveResponse = MedicalDashboardStatsRetrieveResponses[keyof MedicalDashboardStatsRetrieveResponses];

export type ModulesProbeRetrieveData = {
    body?: never;
    path: {
        module_code: string;
    };
    query?: never;
    url: '/api/modules/{module_code}/probe/';
};

export type ModulesProbeRetrieveResponses = {
    200: {
        module?: string;
    };
};

export type ModulesProbeRetrieveResponse = ModulesProbeRetrieveResponses[keyof ModulesProbeRetrieveResponses];

export type ProcedureAssignmentsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/procedure-assignments/';
};

export type ProcedureAssignmentsListResponses = {
    200: PaginatedProcedureAssignmentList;
};

export type ProcedureAssignmentsListResponse = ProcedureAssignmentsListResponses[keyof ProcedureAssignmentsListResponses];

export type ProcedureAssignmentsCreateData = {
    body: ProcedureAssignmentWritable;
    path?: never;
    query?: never;
    url: '/api/procedure-assignments/';
};

export type ProcedureAssignmentsCreateResponses = {
    201: ProcedureAssignment;
};

export type ProcedureAssignmentsCreateResponse = ProcedureAssignmentsCreateResponses[keyof ProcedureAssignmentsCreateResponses];

export type ProcedureAssignmentsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this procedure assignment.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedure-assignments/{id}/';
};

export type ProcedureAssignmentsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProcedureAssignmentsDestroyResponse = ProcedureAssignmentsDestroyResponses[keyof ProcedureAssignmentsDestroyResponses];

export type ProcedureAssignmentsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this procedure assignment.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedure-assignments/{id}/';
};

export type ProcedureAssignmentsRetrieveResponses = {
    200: ProcedureAssignment;
};

export type ProcedureAssignmentsRetrieveResponse = ProcedureAssignmentsRetrieveResponses[keyof ProcedureAssignmentsRetrieveResponses];

export type ProcedureAssignmentsPartialUpdateData = {
    body?: PatchedProcedureAssignmentWritable;
    path: {
        /**
         * A unique integer value identifying this procedure assignment.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedure-assignments/{id}/';
};

export type ProcedureAssignmentsPartialUpdateResponses = {
    200: ProcedureAssignment;
};

export type ProcedureAssignmentsPartialUpdateResponse = ProcedureAssignmentsPartialUpdateResponses[keyof ProcedureAssignmentsPartialUpdateResponses];

export type ProcedureAssignmentsUpdateData = {
    body: ProcedureAssignmentWritable;
    path: {
        /**
         * A unique integer value identifying this procedure assignment.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedure-assignments/{id}/';
};

export type ProcedureAssignmentsUpdateResponses = {
    200: ProcedureAssignment;
};

export type ProcedureAssignmentsUpdateResponse = ProcedureAssignmentsUpdateResponses[keyof ProcedureAssignmentsUpdateResponses];

export type ProceduresListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/procedures/';
};

export type ProceduresListResponses = {
    200: PaginatedProcedureList;
};

export type ProceduresListResponse = ProceduresListResponses[keyof ProceduresListResponses];

export type ProceduresCreateData = {
    body: ProcedureWritable;
    path?: never;
    query?: never;
    url: '/api/procedures/';
};

export type ProceduresCreateResponses = {
    201: Procedure;
};

export type ProceduresCreateResponse = ProceduresCreateResponses[keyof ProceduresCreateResponses];

export type ProceduresDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this procedure.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedures/{id}/';
};

export type ProceduresDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProceduresDestroyResponse = ProceduresDestroyResponses[keyof ProceduresDestroyResponses];

export type ProceduresRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this procedure.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedures/{id}/';
};

export type ProceduresRetrieveResponses = {
    200: Procedure;
};

export type ProceduresRetrieveResponse = ProceduresRetrieveResponses[keyof ProceduresRetrieveResponses];

export type ProceduresPartialUpdateData = {
    body?: PatchedProcedureWritable;
    path: {
        /**
         * A unique integer value identifying this procedure.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedures/{id}/';
};

export type ProceduresPartialUpdateResponses = {
    200: Procedure;
};

export type ProceduresPartialUpdateResponse = ProceduresPartialUpdateResponses[keyof ProceduresPartialUpdateResponses];

export type ProceduresUpdateData = {
    body: ProcedureWritable;
    path: {
        /**
         * A unique integer value identifying this procedure.
         */
        id: number;
    };
    query?: never;
    url: '/api/procedures/{id}/';
};

export type ProceduresUpdateResponses = {
    200: Procedure;
};

export type ProceduresUpdateResponse = ProceduresUpdateResponses[keyof ProceduresUpdateResponses];

export type ProductsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/products/';
};

export type ProductsListResponses = {
    200: PaginatedProductList;
};

export type ProductsListResponse = ProductsListResponses[keyof ProductsListResponses];

export type ProductsCreateData = {
    body: ProductWritable;
    path?: never;
    query?: never;
    url: '/api/products/';
};

export type ProductsCreateResponses = {
    201: Product;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/';
};

export type ProductsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProductsDestroyResponse = ProductsDestroyResponses[keyof ProductsDestroyResponses];

export type ProductsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/';
};

export type ProductsRetrieveResponses = {
    200: Product;
};

export type ProductsRetrieveResponse = ProductsRetrieveResponses[keyof ProductsRetrieveResponses];

export type ProductsPartialUpdateData = {
    body?: PatchedProductWritable;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/';
};

export type ProductsPartialUpdateResponses = {
    200: Product;
};

export type ProductsPartialUpdateResponse = ProductsPartialUpdateResponses[keyof ProductsPartialUpdateResponses];

export type ProductsUpdateData = {
    body: ProductWritable;
    path: {
        /**
         * A unique integer value identifying this product.
         */
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/';
};

export type ProductsUpdateResponses = {
    200: Product;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type ProvidersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/providers/';
};

export type ProvidersListResponses = {
    200: PaginatedProviderList;
};

export type ProvidersListResponse = ProvidersListResponses[keyof ProvidersListResponses];

export type ProvidersCreateData = {
    body: ProviderWritable;
    path?: never;
    query?: never;
    url: '/api/providers/';
};

export type ProvidersCreateResponses = {
    201: Provider;
};

export type ProvidersCreateResponse = ProvidersCreateResponses[keyof ProvidersCreateResponses];

export type ProvidersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this provider.
         */
        id: number;
    };
    query?: never;
    url: '/api/providers/{id}/';
};

export type ProvidersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProvidersDestroyResponse = ProvidersDestroyResponses[keyof ProvidersDestroyResponses];

export type ProvidersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this provider.
         */
        id: number;
    };
    query?: never;
    url: '/api/providers/{id}/';
};

export type ProvidersRetrieveResponses = {
    200: Provider;
};

export type ProvidersRetrieveResponse = ProvidersRetrieveResponses[keyof ProvidersRetrieveResponses];

export type ProvidersPartialUpdateData = {
    body?: PatchedProviderWritable;
    path: {
        /**
         * A unique integer value identifying this provider.
         */
        id: number;
    };
    query?: never;
    url: '/api/providers/{id}/';
};

export type ProvidersPartialUpdateResponses = {
    200: Provider;
};

export type ProvidersPartialUpdateResponse = ProvidersPartialUpdateResponses[keyof ProvidersPartialUpdateResponses];

export type ProvidersUpdateData = {
    body: ProviderWritable;
    path: {
        /**
         * A unique integer value identifying this provider.
         */
        id: number;
    };
    query?: never;
    url: '/api/providers/{id}/';
};

export type ProvidersUpdateResponses = {
    200: Provider;
};

export type ProvidersUpdateResponse = ProvidersUpdateResponses[keyof ProvidersUpdateResponses];

export type PurchaseOrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/purchase-orders/';
};

export type PurchaseOrdersListResponses = {
    200: PaginatedPurchaseOrderList;
};

export type PurchaseOrdersListResponse = PurchaseOrdersListResponses[keyof PurchaseOrdersListResponses];

export type PurchaseOrdersCreateData = {
    body: PurchaseOrderWritable;
    path?: never;
    query?: never;
    url: '/api/purchase-orders/';
};

export type PurchaseOrdersCreateResponses = {
    201: PurchaseOrder;
};

export type PurchaseOrdersCreateResponse = PurchaseOrdersCreateResponses[keyof PurchaseOrdersCreateResponses];

export type PurchaseOrdersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this purchase order.
         */
        id: number;
    };
    query?: never;
    url: '/api/purchase-orders/{id}/';
};

export type PurchaseOrdersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type PurchaseOrdersDestroyResponse = PurchaseOrdersDestroyResponses[keyof PurchaseOrdersDestroyResponses];

export type PurchaseOrdersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this purchase order.
         */
        id: number;
    };
    query?: never;
    url: '/api/purchase-orders/{id}/';
};

export type PurchaseOrdersRetrieveResponses = {
    200: PurchaseOrder;
};

export type PurchaseOrdersRetrieveResponse = PurchaseOrdersRetrieveResponses[keyof PurchaseOrdersRetrieveResponses];

export type PurchaseOrdersPartialUpdateData = {
    body?: PatchedPurchaseOrderWritable;
    path: {
        /**
         * A unique integer value identifying this purchase order.
         */
        id: number;
    };
    query?: never;
    url: '/api/purchase-orders/{id}/';
};

export type PurchaseOrdersPartialUpdateResponses = {
    200: PurchaseOrder;
};

export type PurchaseOrdersPartialUpdateResponse = PurchaseOrdersPartialUpdateResponses[keyof PurchaseOrdersPartialUpdateResponses];

export type PurchaseOrdersUpdateData = {
    body: PurchaseOrderWritable;
    path: {
        /**
         * A unique integer value identifying this purchase order.
         */
        id: number;
    };
    query?: never;
    url: '/api/purchase-orders/{id}/';
};

export type PurchaseOrdersUpdateResponses = {
    200: PurchaseOrder;
};

export type PurchaseOrdersUpdateResponse = PurchaseOrdersUpdateResponses[keyof PurchaseOrdersUpdateResponses];

export type RequisitionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/requisitions/';
};

export type RequisitionsListResponses = {
    200: PaginatedRequisitionList;
};

export type RequisitionsListResponse = RequisitionsListResponses[keyof RequisitionsListResponses];

export type RequisitionsCreateData = {
    body: RequisitionWritable;
    path?: never;
    query?: never;
    url: '/api/requisitions/';
};

export type RequisitionsCreateResponses = {
    201: Requisition;
};

export type RequisitionsCreateResponse = RequisitionsCreateResponses[keyof RequisitionsCreateResponses];

export type RequisitionsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this requisition.
         */
        id: number;
    };
    query?: never;
    url: '/api/requisitions/{id}/';
};

export type RequisitionsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type RequisitionsDestroyResponse = RequisitionsDestroyResponses[keyof RequisitionsDestroyResponses];

export type RequisitionsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this requisition.
         */
        id: number;
    };
    query?: never;
    url: '/api/requisitions/{id}/';
};

export type RequisitionsRetrieveResponses = {
    200: Requisition;
};

export type RequisitionsRetrieveResponse = RequisitionsRetrieveResponses[keyof RequisitionsRetrieveResponses];

export type RequisitionsPartialUpdateData = {
    body?: PatchedRequisitionWritable;
    path: {
        /**
         * A unique integer value identifying this requisition.
         */
        id: number;
    };
    query?: never;
    url: '/api/requisitions/{id}/';
};

export type RequisitionsPartialUpdateResponses = {
    200: Requisition;
};

export type RequisitionsPartialUpdateResponse = RequisitionsPartialUpdateResponses[keyof RequisitionsPartialUpdateResponses];

export type RequisitionsUpdateData = {
    body: RequisitionWritable;
    path: {
        /**
         * A unique integer value identifying this requisition.
         */
        id: number;
    };
    query?: never;
    url: '/api/requisitions/{id}/';
};

export type RequisitionsUpdateResponses = {
    200: Requisition;
};

export type RequisitionsUpdateResponse = RequisitionsUpdateResponses[keyof RequisitionsUpdateResponses];

export type RestRestCheckRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rest/rest-check/';
};

export type RestRestCheckRetrieveResponses = {
    200: Message;
};

export type RestRestCheckRetrieveResponse = RestRestCheckRetrieveResponses[keyof RestRestCheckRetrieveResponses];

export type RfidReadEventsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/rfid-read-events/';
};

export type RfidReadEventsListResponses = {
    200: PaginatedRfidReadEventList;
};

export type RfidReadEventsListResponse = RfidReadEventsListResponses[keyof RfidReadEventsListResponses];

export type RfidReadEventsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rfid read event.
         */
        id: number;
    };
    query?: never;
    url: '/api/rfid-read-events/{id}/';
};

export type RfidReadEventsRetrieveResponses = {
    200: RfidReadEvent;
};

export type RfidReadEventsRetrieveResponse = RfidReadEventsRetrieveResponses[keyof RfidReadEventsRetrieveResponses];

export type RfidReadsCreateData = {
    body: RfidReadWebhook;
    path?: never;
    query?: never;
    url: '/api/rfid-reads/';
};

export type RfidReadsCreateResponses = {
    201: RfidTag;
};

export type RfidReadsCreateResponse = RfidReadsCreateResponses[keyof RfidReadsCreateResponses];

export type RfidTagsListData = {
    body?: never;
    path?: never;
    query?: {
        item_type?: string;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        location?: string;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/rfid-tags/';
};

export type RfidTagsListResponses = {
    200: PaginatedRfidTagList;
};

export type RfidTagsListResponse = RfidTagsListResponses[keyof RfidTagsListResponses];

export type RfidTagsCreateData = {
    body: RfidTagWritable;
    path?: never;
    query?: never;
    url: '/api/rfid-tags/';
};

export type RfidTagsCreateResponses = {
    201: RfidTag;
};

export type RfidTagsCreateResponse = RfidTagsCreateResponses[keyof RfidTagsCreateResponses];

export type RfidTagsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rfid tag.
         */
        id: number;
    };
    query?: never;
    url: '/api/rfid-tags/{id}/';
};

export type RfidTagsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type RfidTagsDestroyResponse = RfidTagsDestroyResponses[keyof RfidTagsDestroyResponses];

export type RfidTagsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rfid tag.
         */
        id: number;
    };
    query?: never;
    url: '/api/rfid-tags/{id}/';
};

export type RfidTagsRetrieveResponses = {
    200: RfidTag;
};

export type RfidTagsRetrieveResponse = RfidTagsRetrieveResponses[keyof RfidTagsRetrieveResponses];

export type RfidTagsPartialUpdateData = {
    body?: PatchedRfidTagWritable;
    path: {
        /**
         * A unique integer value identifying this rfid tag.
         */
        id: number;
    };
    query?: never;
    url: '/api/rfid-tags/{id}/';
};

export type RfidTagsPartialUpdateResponses = {
    200: RfidTag;
};

export type RfidTagsPartialUpdateResponse = RfidTagsPartialUpdateResponses[keyof RfidTagsPartialUpdateResponses];

export type RfidTagsUpdateData = {
    body: RfidTagWritable;
    path: {
        /**
         * A unique integer value identifying this rfid tag.
         */
        id: number;
    };
    query?: never;
    url: '/api/rfid-tags/{id}/';
};

export type RfidTagsUpdateResponses = {
    200: RfidTag;
};

export type RfidTagsUpdateResponse = RfidTagsUpdateResponses[keyof RfidTagsUpdateResponses];

export type SalesOrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/sales-orders/';
};

export type SalesOrdersListResponses = {
    200: PaginatedSalesOrderList;
};

export type SalesOrdersListResponse = SalesOrdersListResponses[keyof SalesOrdersListResponses];

export type SalesOrdersCreateData = {
    body: SalesOrderWritable;
    path?: never;
    query?: never;
    url: '/api/sales-orders/';
};

export type SalesOrdersCreateResponses = {
    201: SalesOrder;
};

export type SalesOrdersCreateResponse = SalesOrdersCreateResponses[keyof SalesOrdersCreateResponses];

export type SalesOrdersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this sales order.
         */
        id: number;
    };
    query?: never;
    url: '/api/sales-orders/{id}/';
};

export type SalesOrdersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SalesOrdersDestroyResponse = SalesOrdersDestroyResponses[keyof SalesOrdersDestroyResponses];

export type SalesOrdersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this sales order.
         */
        id: number;
    };
    query?: never;
    url: '/api/sales-orders/{id}/';
};

export type SalesOrdersRetrieveResponses = {
    200: SalesOrder;
};

export type SalesOrdersRetrieveResponse = SalesOrdersRetrieveResponses[keyof SalesOrdersRetrieveResponses];

export type SalesOrdersPartialUpdateData = {
    body?: PatchedSalesOrderWritable;
    path: {
        /**
         * A unique integer value identifying this sales order.
         */
        id: number;
    };
    query?: never;
    url: '/api/sales-orders/{id}/';
};

export type SalesOrdersPartialUpdateResponses = {
    200: SalesOrder;
};

export type SalesOrdersPartialUpdateResponse = SalesOrdersPartialUpdateResponses[keyof SalesOrdersPartialUpdateResponses];

export type SalesOrdersUpdateData = {
    body: SalesOrderWritable;
    path: {
        /**
         * A unique integer value identifying this sales order.
         */
        id: number;
    };
    query?: never;
    url: '/api/sales-orders/{id}/';
};

export type SalesOrdersUpdateResponses = {
    200: SalesOrder;
};

export type SalesOrdersUpdateResponse = SalesOrdersUpdateResponses[keyof SalesOrdersUpdateResponses];

export type SupplyKitsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        status?: string;
    };
    url: '/api/supply-kits/';
};

export type SupplyKitsListResponses = {
    200: PaginatedSupplyKitList;
};

export type SupplyKitsListResponse = SupplyKitsListResponses[keyof SupplyKitsListResponses];

export type SupplyKitsCreateData = {
    body: SupplyKitWritable;
    path?: never;
    query?: never;
    url: '/api/supply-kits/';
};

export type SupplyKitsCreateResponses = {
    201: SupplyKit;
};

export type SupplyKitsCreateResponse = SupplyKitsCreateResponses[keyof SupplyKitsCreateResponses];

export type SupplyKitsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/';
};

export type SupplyKitsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SupplyKitsDestroyResponse = SupplyKitsDestroyResponses[keyof SupplyKitsDestroyResponses];

export type SupplyKitsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/';
};

export type SupplyKitsRetrieveResponses = {
    200: SupplyKit;
};

export type SupplyKitsRetrieveResponse = SupplyKitsRetrieveResponses[keyof SupplyKitsRetrieveResponses];

export type SupplyKitsPartialUpdateData = {
    body?: PatchedSupplyKitWritable;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/';
};

export type SupplyKitsPartialUpdateResponses = {
    200: SupplyKit;
};

export type SupplyKitsPartialUpdateResponse = SupplyKitsPartialUpdateResponses[keyof SupplyKitsPartialUpdateResponses];

export type SupplyKitsUpdateData = {
    body: SupplyKitWritable;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/';
};

export type SupplyKitsUpdateResponses = {
    200: SupplyKit;
};

export type SupplyKitsUpdateResponse = SupplyKitsUpdateResponses[keyof SupplyKitsUpdateResponses];

export type SupplyKitsAddTagsCreateData = {
    body: SupplyKitWritable;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/add-tags/';
};

export type SupplyKitsAddTagsCreateResponses = {
    200: SupplyKit;
};

export type SupplyKitsAddTagsCreateResponse = SupplyKitsAddTagsCreateResponses[keyof SupplyKitsAddTagsCreateResponses];

export type SupplyKitsRemoveTagsCreateData = {
    body: SupplyKitWritable;
    path: {
        /**
         * A unique integer value identifying this supply kit.
         */
        id: number;
    };
    query?: never;
    url: '/api/supply-kits/{id}/remove-tags/';
};

export type SupplyKitsRemoveTagsCreateResponses = {
    200: SupplyKit;
};

export type SupplyKitsRemoveTagsCreateResponse = SupplyKitsRemoveTagsCreateResponses[keyof SupplyKitsRemoveTagsCreateResponses];

export type TechniciansListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/technicians/';
};

export type TechniciansListResponses = {
    200: PaginatedTechnicianList;
};

export type TechniciansListResponse = TechniciansListResponses[keyof TechniciansListResponses];

export type TechniciansCreateData = {
    body: TechnicianWritable;
    path?: never;
    query?: never;
    url: '/api/technicians/';
};

export type TechniciansCreateResponses = {
    201: Technician;
};

export type TechniciansCreateResponse = TechniciansCreateResponses[keyof TechniciansCreateResponses];

export type TechniciansDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this technician.
         */
        id: number;
    };
    query?: never;
    url: '/api/technicians/{id}/';
};

export type TechniciansDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type TechniciansDestroyResponse = TechniciansDestroyResponses[keyof TechniciansDestroyResponses];

export type TechniciansRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this technician.
         */
        id: number;
    };
    query?: never;
    url: '/api/technicians/{id}/';
};

export type TechniciansRetrieveResponses = {
    200: Technician;
};

export type TechniciansRetrieveResponse = TechniciansRetrieveResponses[keyof TechniciansRetrieveResponses];

export type TechniciansPartialUpdateData = {
    body?: PatchedTechnicianWritable;
    path: {
        /**
         * A unique integer value identifying this technician.
         */
        id: number;
    };
    query?: never;
    url: '/api/technicians/{id}/';
};

export type TechniciansPartialUpdateResponses = {
    200: Technician;
};

export type TechniciansPartialUpdateResponse = TechniciansPartialUpdateResponses[keyof TechniciansPartialUpdateResponses];

export type TechniciansUpdateData = {
    body: TechnicianWritable;
    path: {
        /**
         * A unique integer value identifying this technician.
         */
        id: number;
    };
    query?: never;
    url: '/api/technicians/{id}/';
};

export type TechniciansUpdateResponses = {
    200: Technician;
};

export type TechniciansUpdateResponse = TechniciansUpdateResponses[keyof TechniciansUpdateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];
