# Generated by Django 5.2.16 on 2026-07-09 03:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=128)),
                ('item_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('en_stock', 'En stock'), ('en_transito', 'En tránsito'), ('en_uso', 'En uso'), ('dado_de_baja', 'Dado de baja')], default='en_stock', max_length=32)),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-last_read_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RFIDReadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('reader_source', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_events', to='inventory.rfidtag')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='rfidtag',
            index=models.Index(fields=['organization', 'status'], name='inventory_r_organiz_957382_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidtag',
            index=models.Index(fields=['organization', 'code'], name='inventory_r_organiz_e510eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfidtag',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_rfid_tag_code_per_organization'),
        ),
        migrations.AddIndex(
            model_name='rfidreadevent',
            index=models.Index(fields=['tag', 'timestamp'], name='inventory_r_tag_id_b3ef9f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidreadevent',
            index=models.Index(fields=['organization', 'timestamp'], name='inventory_r_organiz_d84bd4_idx'),
        ),
    ]
