# Generated by Django 5.2.16 on 2026-07-13 18:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumental', '0003_catalogs_and_locations'),
        ('inventory', '0001_initial'),
        ('organizations', '0003_platform_admin_demo_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='catalog_item',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo al que pertenece esta unidad física.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_units', to='instrumental.instrumentcatalogitem'),
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('location_type', models.CharField(choices=[('warehouse', 'Almacén'), ('zone', 'Zona / anaquel'), ('hospital', 'Hospital'), ('vehicle', 'Vehículo'), ('other', 'Otro')], default='warehouse', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='inventory_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='inventory.inventorylocation'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_inventory_location_code_per_org'),
        ),
    ]
