# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_catalogs_and_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidtag",
            name="lot",
            field=models.CharField(
                blank=True,
                help_text="Número de lote del producto (si aplica).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="rfidtag",
            name="expires_on",
            field=models.DateField(
                blank=True,
                help_text="Fecha de caducidad (si aplica).",
                null=True,
            ),
        ),
    ]
