# Generated by Django 5.2.16 on 2026-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='movement_type',
            field=models.CharField(choices=[('salida', 'Salida'), ('entrada', 'Entrada')], default='salida', max_length=16),
        ),
    ]
