# Generated by Django 5.2.16 on 2026-07-09 03:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=128)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('procedure_type', models.CharField(max_length=255)),
                ('destination_hospital', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_preparation', 'En preparación'), ('in_transit', 'En tránsito'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'procedures',
                'ordering': ['-scheduled_date', 'procedure_type'],
            },
        ),
        migrations.CreateModel(
            name='SupplyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('armando', 'Armando'), ('lista', 'Lista'), ('en_transito', 'En tránsito'), ('entregada', 'Entregada'), ('usada', 'Usada')], default='armando', max_length=32)),
                ('destination_hospital', models.CharField(blank=True, max_length=255)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_kits', to='medical.procedure')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SupplyKitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('supply_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_tags', to='medical.supplykit')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_memberships', to='inventory.rfidtag')),
            ],
        ),
        migrations.AddField(
            model_name='supplykit',
            name='tags',
            field=models.ManyToManyField(related_name='supply_kits', through='medical.SupplyKitTag', to='inventory.rfidtag'),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[('lead_technician', 'Técnico principal'), ('assistant', 'Asistente'), ('supervisor', 'Supervisor')], max_length=32)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='medical.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='medical.procedure')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='medical.technician')),
            ],
            options={
                'ordering': ['procedure', 'role'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplykittag',
            constraint=models.UniqueConstraint(fields=('supply_kit', 'tag'), name='unique_supply_kit_tag'),
        ),
        migrations.AddConstraint(
            model_name='supplykit',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_supply_kit_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='procedureassignment',
            constraint=models.UniqueConstraint(fields=('procedure', 'technician', 'doctor', 'role'), name='unique_procedure_assignment'),
        ),
    ]
