# Generated by Django 5.2.16 on 2026-07-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor que ocupará el instrumental en el procedimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='medical.doctor'),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supply_kits', to='medical.technician'),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='hospital_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='return_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplykit',
            name='warehouse_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplykit',
            name='status',
            field=models.CharField(choices=[('armando', 'Armando'), ('lista', 'Lista'), ('en_transito', 'En tránsito'), ('entregada', 'Entregada en hospital'), ('retornando', 'Retornando a almacén'), ('devuelta', 'Confirmada en almacén'), ('usada', 'Usada')], default='armando', max_length=32),
        ),
    ]
