# Generated by Django 5.2.16 on 2026-07-10 03:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('medical', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('is_central', models.BooleanField(default=False, help_text='Marca la sede CRCAO / almacén central.')),
                ('city', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sku', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('instrument', 'Instrumental'), ('equipment', 'Equipo médico'), ('tray', 'Charola')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('requires_sterilization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_catalog_items', to='inventory.rfidtag')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentProcedureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Solicitada'), ('quotation', 'En cotización'), ('quotation_accepted', 'Cotización aceptada'), ('fulfillment', 'En asignación'), ('in_field', 'En campo'), ('returning', 'En retorno'), ('validated', 'Validado CRCAO'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_out_hours', models.PositiveIntegerField(default=24)),
                ('destination_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_requests', to='instrumental.hospitalsite')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_requests', to='medical.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_requests', to='medical.procedure')),
                ('proximity_next_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximity_previous_requests', to='instrumental.instrumentprocedurerequest')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('planning', 'Planificando'), ('ready', 'Listo'), ('dispatched', 'Despachado'), ('at_hospital', 'En hospital'), ('returning', 'Retornando'), ('validated', 'Validado')], default='planning', max_length=32)),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('scheduled_return', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lead_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_fulfillment_plans', to='medical.technician')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_plan', to='instrumental.instrumentprocedurerequest')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_doctor', 'Pendiente doctor'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='draft', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='instrumental.instrumentprocedurerequest')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='instrumental.instrumentcatalogitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='instrumental.instrumentprocedurerequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tray_code', models.CharField(blank=True, max_length=64)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('requires_sterilization', models.BooleanField(default=False)),
                ('sterilization_status', models.CharField(choices=[('not_required', 'No requiere'), ('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('ready', 'Listo')], default='not_required', max_length=32)),
                ('status', models.CharField(choices=[('assigned', 'Asignado'), ('sterilizing', 'Esterilizando'), ('loaded', 'Cargado'), ('in_transit', 'En tránsito'), ('at_hospital', 'En hospital'), ('returning', 'Retornando'), ('returned', 'Retornado'), ('validated', 'Validado')], default='assigned', max_length=32)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='instrumental.instrumentcatalogitem')),
                ('current_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_dispatches', to='instrumental.hospitalsite')),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='instrumental.fulfillmentplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_dispatches', to='inventory.rfidtag')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_dispatches', to='medical.technician')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HandheldScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('identifier_used', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('load_departure', 'Salida CRCAO'), ('hospital_arrival', 'Llegada hospital'), ('hospital_departure', 'Salida hospital'), ('return_arrival', 'Retorno CRCAO'), ('crcao_validation', 'Validación CRCAO')], max_length=32)),
                ('handheld_id', models.CharField(blank=True, max_length=64)),
                ('location_notes', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumental_scan_events', to='inventory.rfidtag')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handheld_scans', to='instrumental.hospitalsite')),
                ('material_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='instrumental.materialdispatch')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProximityScheduleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('minutes_between', models.PositiveIntegerField(default=60)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('from_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_outgoing_links', to='instrumental.instrumentprocedurerequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('reuse_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximity_links', to='instrumental.materialdispatch')),
                ('to_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_incoming_links', to='instrumental.instrumentprocedurerequest')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requires_sterilization', models.BooleanField(default=False)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='instrumental.instrumentcatalogitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='instrumental.instrumentquotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=64)),
                ('plate', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('transporter_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_vehicles', to='inventory.rfidtag')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='fulfillmentplan',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_plans', to='instrumental.transportvehicle'),
        ),
        migrations.AddConstraint(
            model_name='hospitalsite',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_hospital_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='instrumentcatalogitem',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='unique_instrument_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='proximityschedulelink',
            constraint=models.UniqueConstraint(fields=('from_request', 'to_request'), name='unique_proximity_link'),
        ),
        migrations.AddConstraint(
            model_name='transportvehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_vehicle_code_per_org'),
        ),
    ]
