# Generated by Django 5.2.16 on 2026-07-10 15:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumental', '0001_initial'),
        ('medical', '0002_procedure_doctor_supplykit_assigned_technician_and_more'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalogitem',
            name='default_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base si no hay contrato aplicable.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='price_source',
            field=models.CharField(blank=True, help_text='Origen del precio: doctor_hospital, doctor, hospital, catalog, default.', max_length=32),
        ),
        migrations.CreateModel(
            name='InstrumentPriceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Si se omite, el contrato aplica a cualquier doctor del hospital.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_price_contracts', to='medical.doctor')),
                ('hospital', models.ForeignKey(blank=True, help_text='Si se omite, el contrato aplica a cualquier hospital del doctor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_price_contracts', to='instrumental.hospitalsite')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='instrumental.instrumentcatalogitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='instrumental.instrumentpricecontract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='instrumentquotation',
            name='applied_contract',
            field=models.ForeignKey(blank=True, help_text='Contrato principal usado al generar la cotización (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='instrumental.instrumentpricecontract'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='applied_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='instrumental.instrumentpricecontract'),
        ),
        migrations.AddConstraint(
            model_name='instrumentpricecontract',
            constraint=models.CheckConstraint(condition=models.Q(('doctor__isnull', False), ('hospital__isnull', False), _connector='OR'), name='contract_requires_doctor_or_hospital'),
        ),
        migrations.AddConstraint(
            model_name='instrumentpricecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False), ('hospital__isnull', False), ('is_active', True)), fields=('organization', 'doctor', 'hospital'), name='unique_active_contract_doctor_hospital'),
        ),
        migrations.AddConstraint(
            model_name='instrumentpricecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False), ('hospital__isnull', True), ('is_active', True)), fields=('organization', 'doctor'), name='unique_active_contract_doctor_only'),
        ),
        migrations.AddConstraint(
            model_name='instrumentpricecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', True), ('hospital__isnull', False), ('is_active', True)), fields=('organization', 'hospital'), name='unique_active_contract_hospital_only'),
        ),
        migrations.AddConstraint(
            model_name='instrumentcontractline',
            constraint=models.UniqueConstraint(fields=('contract', 'catalog_item'), name='unique_contract_catalog_item'),
        ),
    ]
