# Generated by Django 5.2.16 on 2026-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumental', '0002_price_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalogitem',
            name='brand',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='instrumentcatalogitem',
            name='category',
            field=models.CharField(blank=True, help_text='Grupo o especialidad (ej. Cardiología, Ortopedia).', max_length=128),
        ),
        migrations.AddField(
            model_name='instrumentcatalogitem',
            name='unit',
            field=models.CharField(default='pza', max_length=32),
        ),
        migrations.AlterField(
            model_name='handheldscanevent',
            name='event_type',
            field=models.CharField(choices=[('load_departure', 'Salida de almacén'), ('hospital_arrival', 'Llegada hospital'), ('hospital_departure', 'Salida hospital'), ('return_arrival', 'Retorno a almacén'), ('crcao_validation', 'Validación en almacén')], max_length=32),
        ),
        migrations.AlterField(
            model_name='hospitalsite',
            name='is_central',
            field=models.BooleanField(default=False, help_text='Marca el almacén central de la organización.'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalogitem',
            name='item_type',
            field=models.CharField(choices=[('instrument', 'Instrumental'), ('equipment', 'Equipo médico'), ('tray', 'Charola'), ('consumable', 'Consumible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='instrumentprocedurerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Solicitada'), ('quotation', 'En cotización'), ('quotation_accepted', 'Cotización aceptada'), ('fulfillment', 'En asignación'), ('in_field', 'En campo'), ('returning', 'En retorno'), ('validated', 'Validado en almacén'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=32),
        ),
    ]
